config/routes.rb
Rails.application.routes.draw do
  resources :registries do
    resources :enrollments, only: [:new, :create, :index]
    resources :participants, only: [:index]
  resources :coordinators
  end

  get 'export_participants', to: 'participants#export'
  root 'registries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coordinator.rb
class Coordinator < ApplicationRecord
  has_many :enrollments
  has_many :participants, through: :enrollments
  has_many :registries, through: :enrollments
  validates :email, presence: true, uniqueness: true

end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :coordinator
  belongs_to :participant
  belongs_to :registry
  validates :participant, uniqueness: { scope: :registry, message: "has already been enrolled in this registry." }

end

app/models/participant.rb
class Participant < ApplicationRecord
  has_many :enrollments
  has_many :coordinators, through: :enrollments
  has_many :registries, through: :enrollments
  validates :name, uniqueness: { scope: :registries, message: "has already been enrolled in this registry." }

end

app/models/registry.rb
class Registry < ApplicationRecord
  has_many :enrollments
  has_many :participants, through: :enrollments
  has_many :coordinators, through: :enrollments
  enum status: [:close, :open]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coordinators_controller.rb
class CoordinatorsController < ApplicationController
  def new
    @coordinator = Coordinator.new
  end

  def create
    @coordinator = Coordinator.new(coordinator_params)
    if @coordinator.save
      redirect_to @coordinator, notice: "Coordinator was successfully created."
    else
      render :new
    end
  end

  private

  def coordinator_params
    params.require(:coordinator).permit(:name, :email, :phone_number, registry_ids: [])
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_registry
  before_action :set_coordinator, only: [:new, :create]
  
  def new
    @enrollment = Enrollment.new
    @participants = Participant.all
  end

  def create
    @enrollment = @coordinator.enrollments.build(enrollment_params)
    if @enrollment.save
      redirect_to registry_enrollments_path(@registry), notice: "Participant was successfully enrolled."
    else
      @participants = Participant.all
      render :new
    end
  end

  def index
    @enrollments = @registry.enrollments.includes(:coordinator, :participant).order(:created_at)
    @enrollments_by_coordinator = @enrollments.group_by(&:coordinator)
  end

  private

  def set_registry
    @registry = Registry.find(params[:registry_id])
  end

  def set_coordinator
    @coordinator = Coordinator.find(params[:coordinator_id])
  end

  def enrollment_params
    params.require(:enrollment).permit(:participant_id, :date_of_enrollment, :method_of_contact, :remarks)
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  def index
    @registry = Registry.find(params[:registry_id])
    @participants = @registry.participants.group_by(&:coordinator)
  end

  def export
    @coordinators = Coordinator.all
    respond_to do |format|
      format.csv { send_data participants_to_csv, filename: "participants.csv" }
    end
  end

  private

  def participants_to_csv
    CSV.generate(headers: true) do |csv|
      csv << ["Name", "Gender", "Date of Birth", "Enrollment Date", "Method of Contact", "Remarks", "Coordinator"]
      @coordinators.each do |coordinator|
        coordinator.participants.each do |participant|
          csv << [participant.name, participant.gender, participant.date_of_birth, participant.enrollments.first.date_of_enrollment, participant.enrollments.first.method_of_contact, participant.enrollments.first.remarks, coordinator.name]
        end
      end
    end
  end
end

app/controllers/registries_controller.rb
class RegistriesController < ApplicationController
  def index
    @registries = Registry.all
  end

  def show
  @registry = Registry.find(params[:id])
  @coordinators = @registry.coordinators
  @enrollments_by_coordinator = Enrollment.includes(:participant).where(registry_id: @registry.id).group_by(&:coordinator)
end


  def new
    @registry = Registry.new
  end

  def create
    @registry = Registry.new(registry_params)
    if @registry.save
      redirect_to @registry, notice: "Registry was successfully created."
    else
      render :new
    end
  end

  private

  def registry_params
    params.require(:registry).permit(:name, :location, :state,:status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coordinators_helper.rb
module CoordinatorsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/registries_helper.rb
module RegistriesHelper
end

app/views/coordinators/index.html.erb
<h1>Coordinators</h1>
<ul>
  <% @coordinators.each do |coordinator| %>
    <li>
      <%= link_to coordinator.name, coordinator_path(coordinator) %>
      - <%= coordinator.email %>
      - <%= coordinator.phone_number %>
    </li>
  <% end %>
</ul>

app/views/coordinators/new.html.erb
<h1>New Coordinator</h1>

<%= form_with model: @coordinator, url: coordinators_path, local: true do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :registry_ids, "Registries" %><br>
    <%= form.collection_check_boxes :registry_ids, Registry.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit "Create Coordinator" %>
  </div>
<% end %>

app/views/coordinators/show.html.erb
<h1><%= @coordinator.name %> Details</h1>
<p>Email: <%= @coordinator.email %></p>
<p>Phone Number: <%= @coordinator.phone_number %></p>

<h2>Enroll Participant</h2>
<%= link_to "Enroll Participant", new_registry_coordinator_enrollment_path(@registry, @coordinator) %>

app/views/enrollments/new.html.erb
<h1>New Enrollment</h1>

<%= form_with(model: [@registry, @coordinator, @enrollment], url: registry_enrollments_path(@registry, @coordinator), local: true) do |form| %>
  <div class="field">
    <%= form.label :participant_id %>
    <%= form.collection_select :participant_id, @participants, :id, :name %>
  </div>


  <div class="field">
    <%= form.label :date_of_enrollment %>
    <%= form.date_field :date_of_enrollment %>
  </div>

  <div class="field">
    <%= form.label :method_of_contact %>
    <%= form.select :method_of_contact, ["phone", "email"] %>
  </div>

  <div class="field">
    <%= form.label :remarks %>
    <%= form.text_area :remarks %>
  </div>

  <div class="actions">
    <%= form.submit "Enroll Participant" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParticipantTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/participants/index.html.erb
<h1>Participants for <%= @registry.name %></h1>
<% @participants.each do |coordinator, participants| %>
  <h3><%= coordinator.name %></h3>
  <ul>
    <% participants.each do |participant| %>
      <li><%= participant.name %> - <%= participant.gender %> - <%= participant.date_of_birth %></li>
    <% end %>
  </ul>
<% end %>
<%= link_to "Export Participants", export_participants_path(format: :csv) %>

app/views/registries/index.html.erb
<h1>Registries</h1>
<ul>
  <% @registries.each do |registry| %>
    <li>
      <%= link_to registry.name, registry_path(registry) %>
      - <%= registry.location %>
      - <%= registry.state %>
      <%= registry.status %>
<%= link_to 'View Participants', registry_participants_path(registry) %>
    </li>
  <% end %>

  <%=link_to"add the registry",new_registry_path%>
</ul>

app/views/registries/new.html.erb
<h1>New Registry</h1>

<%= form_with model: @registry, url: registries_path, local: true do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="actions">
    <%= form.submit "Create Registry" %>
  </div>
<% end %>

app/views/registries/show.html.erb
<h1><%= @registry.name %> Participants</h1>

<% @enrollments_by_coordinator.each do |coordinator, enrollments| %>
  <h3><%= coordinator.name %></h3>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Gender</th>
        <th>Date of Birth</th>
        <th>Date of Enrollment</th>
        <th>Method of Contact</th>
        <th>Remarks</th>
      </tr>
    </thead>
    <tbody>
      <% enrollments.each do |enrollment| %>
        <tr>
          <td><%= enrollment.participant.name %></td>
          <td><%= enrollment.participant.gender %></td>
          <td><%= enrollment.participant.date_of_birth %></td>
          <td><%= enrollment.date_of_enrollment %></td>
          <td><%= enrollment.method_of_contact %></td>
          <td><%= enrollment.remarks %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>